notifications:
  email:
  - apple.builds@sagebase.org
language: objective-c
osx_image: xcode9.3
xcode_project: CardiorespiratoryFitness/CardiorespiratoryFitness.xcodeproj 
xcode_scheme: CRFTestApp
cache:
- bundler
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
install:
- gem install bundler
- bundle install
script:
- travis_wait 30 ./travis/build.sh
branches:
  only:
  - master
  - "/^stable-.*$/"
