module: CardiorespiratoryFitness
output: Documentation
xcodebuild_arguments:
- -workspace
- CardiorespiratoryFitness.xcworkspace
- -scheme
- "CardiorespiratoryFitness"

author: "Sage Bionetworks"
author_url: https://developer.sagebridge.org
github_url: https://github.com/Sage-Bionetworks/CardiorespiratoryFitness-iOS.git
copyright: "&copy; 2017-2019 [Sage Bionetworks](https://developer.sagebridge.org). All rights reserved."
min_acl: public
clean: true
skip_undocumented: true
hide_documentation_coverage: true
